# for creating these resources it requires the user to be logged in as system admin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-new-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: my-new-operator-edit-resources
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: my-new-operator
    namespace: default
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-new-operator
  labels: &default-labels
    app.kubernetes.io/name: my-new-operator
    app.kubernetes.io/version: v0.0.1-v1alpha1
spec:
  replicas: 1
  selector:
    matchLabels: *default-labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *default-labels
    spec:
      serviceAccountName: my-new-operator
      containers:
      - name: my-new-operator
        image: io-acme/my-new-operator:latest
        env:
        - name: CRD
          value: "true"
        imagePullPolicy: IfNotPresent

